sudo: required

language: python

cache:
  pip: true

python:
  - "3.7"

install:
  - pip install pipenv
  - pip install pytest pytest-cov codecov
  - pipenv install

script:
  - pipenv run pytest --cov=./

after_success:
  - codecov