ext: ext.swissvoice

env:
  STATISTICS_URL: https://swiss-voice.ch/api/stats

notifications:
  webhook:
    url: $WEBHOOK_URL

tasks:
  statistics:
    run: weekly

    report:
      title: "Generated Statistics"
      fields:
        Proposed Texts: "{result.json.data.total_proposed}"
        Samples:        "{result.json.data.total_samples}"
        Texts:          "{result.json.data.total_texts}"
        Votes:          "{result.json.data.total_votes}"

    job:
      slave:  dobby.get_url
      url:    $STATISTICS_URL

  text_trial:
    run:    monthly

    report:
      title: "Proposed Text Trial"
      fields:
        Accepted: "{accept_texts.result}"
        Rejected: "{reject_texts.result}"

    jobs:
      accept_texts:
        slave:      dobby.mongodb.move_documents
        database:   $SWISSVOICE_DB_URI
        from_coll:  proposed_texts
        to_coll:    texts
        condition:
          votes: { $gte: 10 }
          $expr: { $gte: [{ $divide: ["$balance", "$votes"] }, .8] }
        projection:
          - region
          - text

      reject_texts:
        slave:      dobby.mongodb.remove_documents
        database:   $SWISSVOICE_DB_URI
        from_coll:  proposed_texts
        condition:
          $or:
            - {
                votes: { $gte: 10 },
                $expr: { $lt: [{ $divide: ["$balance", "$votes"] }, .5] }
              }
            - { votes: { $gt: 25 } }

  zip:
    run: monthly
    job: swissvoice.zip